### ISSUE TITLE
Multicall1 address on 1337

### ISSUE THREAD

**Issue by Majorfi** [Destiner/ethcall#158] opened 2022-11-24 13:19 UTC
Hello!

While playing with `getEthBalance`, I noticed that this function is using the `multicall1` contract (even with `tryAll`) which is set to address `0x77dCa2C955b15e9dE4dbBCf1246B4B85b651e50e` on the [multicall addresses file](https://github.com/Destiner/ethcall/blob/22fb5ee8aa46b0e77a219620cd281c0a21e1a7c4/src/multicall.ts#L90).

This contract is not deployed on mainnet but only on testsnets.
Wondering if this should be moved to `0xeefba1e63905ef1d7acba5a8513c70307c1ce441` (mainnet multicall1) or if `getEthBalance` should respect `all`, `tryAll` or `tryEach`!

Thank you for your work!

**Comment by Destiner** [comment] 2022-11-26 12:20
Hey @Majorfi! Did you tried to query ether balance using ethcall on mainnet, and it failed due to trying to use `0x77dCa2C955b15e9dE4dbBCf1246B4B85b651e50e`?

From the code, this address is used on `1337` chain, which is a local devnet if I'm not mistaken. On mainnet, we indeed use `0xeefba1e63905ef1d7acba5a8513c70307c1ce441 ` ([source](https://github.com/Destiner/ethcall/blob/22fb5ee8aa46b0e77a219620cd281c0a21e1a7c4/src/multicall.ts#LL9-L11)) as you could expect.

Are you sure you were querying mainnet? If so, could you please provide a snippet or a repo to reproduce?

**Comment by Destiner** [comment] 2022-12-19 16:42
@Majorfi thanks for such a detailed answer! I think I get it now.

Probably the easiest fix would be to switch the order of multicall contracts for `getEthBalance`, so that the Multicall 3 would be the default.

But I have to think whether this might break something. In the meantime, feel free to give any other ideas.

**Comment by Destiner** [comment] 2023-03-11 11:36
Fixed in `5.0.1`

**Closed by Destiner** 2023-03-11 11:36 UTC
Labels: bug
